### ISSUE TITLE
Fix structured data added to the "Reviews" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/to-reviews#1]
[TO Demo](https://to-demo.lsdev.biz/review/margarettes-trip-tanzania/)
[Google Structured Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Freview%2Fmargarettes-trip-south-africa%2F)

**Comment by krugazul** [comment]
The reviews structure has been added,  but we need to fix duplicate `itemReviewed` tags.

[Review Page](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Freview%2Fmargarettes-trip-south-africa%2F) - Structure Tool Test

**Comment by krugazul** [comment]
@ashleyshaw the following fields have been added to the review schema,  I have gone through the custom fields as well to add in as much relevant info as possible.

Complete
 - `headline` ( post title )
 - `itemReviewed` ( connected tours + accommodation as `Products`)
 - `reviewBody` (content / excerpt)
 - `reviewRating` (Rating custom fields)
 - `author` (reviewer name and email address custom fields)
 - `offers` (the connected specials)
 - `spatialCoverage` ( destinations connected as Country and State )
 - `temporalCoverage` ( date of visit dates )

**Team** - I cant find a field to connected the "Team" member, as some who published or reviewed the review.  And neither as a "Person" who is being reviewd, meaning you cannot Review a person yet, only articles, places, products [etc](https://schema.org/Review#incoming)
**Articles** - We shouldnt really have our TO Reviews connected to articles in this way,  because its not relevant, the review is of an accommodation or a tour.   An articles reviews would be its WordPress "comments".
